name: Create PR with gh CLI

on:
  repository_dispatch:
    types: [create-pr]

permissions:
  contents: write       # Allows push access to repository
  pull-requests: write  # Allows creating pull requests

jobs:
  create-pr:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608  # v4.1.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      # Step 3: Configure git user name and email
      - name: Configure Git user
        run: |
          git config --global user.email "github-actions@github.com"
          git config --global user.name "github-actions"

      # Step 4: Create and push a new branch using git
      - name: Create and push new branch
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Set GH_TOKEN here
        run: |
          # Get the current date and time
          DATE=$(date +"%Y-%m-%d-%H-%M-%S")
          # Create a new feature branch with the current date
          git checkout -b feature-branch-$DATE

          # Add a new line to README.md
          echo "Branch got created from storyblock on $DATE" >> README.md
          git add README.md
          git commit -m "Add new line to README.md with date and time"

          # Push the branch to remote
          git push -u origin feature-branch-$DATE
      # Step 5: Create Pull Request using gh CLI
      - name: Create Pull Request
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Set GH_TOKEN here
        run: |
          # Get the current date and time for the PR body
          DATE=$(date +"%Y-%m-%d %H:%M:%S")
          
          gh pr create \
            --title "Update README.md with date and time" \
            --body "This PR adds a new line to the README.md file with the date and time: $DATE. Branch got created from storyblock." \
            --head feature-branch-$DATE \
            --base main
