name: Create PR with gh CLI

on:
  repository_dispatch:
    types: [create-pr]

permissions:
  contents: write       # Allows push access to repository
  pull-requests: write  # Allows creating pull requests

jobs:
  create-pr:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608  # v4.1.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      # Step 2: Configure git user name and email
      - name: Configure Git user
        run: |
          git config --global user.email "github-actions@github.com"
          git config --global user.name "github-actions"

      # Step 3: Create and push a new branch using git
      - name: Create and push new branch
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Set GH_TOKEN here
        run: |
          # Get the current date and time
          DATE=$(date +"%Y-%m-%d-%H-%M-%S")
          # Create a new feature branch with the current date
          git checkout -b feature-branch-$DATE

          # Add a new line to README.md
          echo "Branch got created from storyblock on $DATE" >> README.md
          git add README.md
          git commit -m "Add new line to README.md with date and time"

          # Check git status and log to ensure commit happened
          git status
          git log --oneline

          # Push the branch to remote
          git push -u origin feature-branch-$DATE

      # Step 4: Ensure the latest branches are fetched
      - name: Fetch latest branches
        run: |
          git fetch --all
          
      # Step 5: Check remote branches to verify push
      - name: List remote branches
        run: |
          git branch -r

      # Step 6: Ensure the feature branch exists on remote
      - name: Ensure feature branch exists
        run: |
          git fetch origin feature-branch-$DATE
          git branch -r

      # Step 7: Check commit differences between main and feature branch
      - name: Check commit differences between main and feature branch
        run: |
          git fetch origin main  # Fetch the latest main branch
          git checkout feature-branch-$DATE  # Ensure we're on the feature branch
          git log --oneline main..feature-branch-$DATE  # Show the difference in commits

      # Step 8: Create Pull Request using gh CLI
      - name: Create Pull Request
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Set GH_TOKEN here
        run: |
          # Get the current date and time for the PR body
          DATE=$(date +"%Y-%m-%d-%H-%M-%S")
          
          # Create the PR with gh CLI
          gh pr create \
            --title "Update README.md with date and time" \
            --body "This PR adds a new line to the README.md file with the date and time: $DATE. Branch got created from storyblock." \
            --head feature-branch-$DATE \
            --base main
