name: Create PR on Dispatch

on:
  repository_dispatch:
    types: [create-pr]

jobs:
  create-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.PAT }}

      - name: Set up Git user
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"

      - name: Fetch all remote branches
        run: git fetch --prune --unshallow

      - name: Create and push a new branch
        run: |
          # Create a new branch
          git checkout -b feature-branch
          echo "This is a new line added by the workflow." >> README.md
          git add README.md
          git commit -m "Add new line to README.md"

          # Push the new branch to the remote repository
          git push https://x-access-token:${{ secrets.PAT }}@github.com/Vaibhavweb-sys/test-workflow.git feature-branch

      - name: Verify remote branch existence
        run: |
          # Ensure the remote branch exists
          git fetch origin feature-branch
          git branch -r

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.PAT }}
          commit-message: "Add new feature"
          branch: feature-branch
          base: main
          title: "Update README.md"
          body: "This PR adds a new line to the README.md file."
