name: Create PR with gh CLI

on:
  repository_dispatch:
    types: [create-pr]

jobs:
  create-pr:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Pull latest changes
      - name: Pull latest from main
        run: |
          git fetch --prune --unshallow
          git checkout main
          git pull origin main

      # Step 3: Create and push a new branch
      - name: Create and push new branch
        run: |
          # Create the feature branch
          git checkout -b feature-branch

          # Add a new line to README.md
          echo "This is a new line added by the workflow using gh CLI." >> README.md
          git add README.md
          git commit -m "Add new line to README.md"

          # Push the branch to remote
          git push -u origin feature-branch

      # Step 4: Install GitHub CLI
      - name: Install GitHub CLI
        run: |
          sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-key C99B11DEB97541F0
          sudo apt-add-repository https://cli.github.com/packages
          sudo apt update
          sudo apt install gh

      # Step 5: Authenticate GitHub CLI
      - name: Authenticate GitHub CLI
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh auth login --with-token <<< "$GITHUB_TOKEN"

      # Step 6: Create Pull Request using gh CLI
      - name: Create Pull Request
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh pr create \
            --title "Update README.md" \
            --body "This PR adds a new line to the README.md file." \
            --head feature-branch \
            --base main
