name: Create PR with gh CLI

on:
  repository_dispatch:
    types: [create-pr]

permissions:
  contents: write       # Allows push access to repository
  pull-requests: write  # Allows creating pull requests

jobs:
  create-pr:
    runs-on: ubuntu-latest
    outputs:
      date: ${{ steps.set-date.outputs.date }}
    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608  # v4.1.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0
      # Step 2: Set the date
      - name: Set date
        id: set-date
        run: echo "date=$(date +'%Y-%m-%d-%H-%M-%S')" >> $GITHUB_ENV
        
      # Step 3: Configure git user name and email
      - name: Configure Git user
        run: |
          git config --global user.email "github-actions@github.com"
          git config --global user.name "github-actions"

      # Step 4: Create and push a new branch using git
      - name: Create and push new branch
        run: |
          DATE=${{ env.date }}  # Retrieve date from environment variable
          echo "Branch Date: $DATE"
          
          # Create a new feature branch with the current date
          git checkout -b feature-branch-$DATE

          # Add a publish log to storyblok-published-log file
          echo "Story got published from storyblock cms on $DATE " >> storyblok-published-log
          git add storyblok-published-log
          git commit -m "Add log to storyblok-published-log"

          # Push the branch to remote
          git push -f origin feature-branch-$DATE

      # Step 5: Create Pull Request using gh CLI
      - name: Create Pull Request
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          DATE=${{ env.date }}  # Retrieve date from environment variable
          gh pr create \
            --title "Update storyblok-published-log  with date and time" \
            --body "Story:published: storyblok cms on $DATE" \
            --head feature-branch-$DATE \
            --base main
