name: Create PR on Dispatch

on:
  repository_dispatch:
    types: [create-pr]

jobs:
  create-pr:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.PAT }}

      # Step 2: Set up Git user
      - name: Set up Git user
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"

      # Step 3: Pull the latest code from main
      - name: Pull latest from main
        run: |
          git fetch --prune --unshallow
          git checkout main
          git pull origin main

      # Step 4: Create and push the new branch
      - name: Create and push a new branch
        run: |
          # Create the feature branch
          git checkout -b feature-branch

          # Add a new line to README.md
          echo "This is a new line added by the workflow." >> README.md
          git add README.md
          git commit -m "Add new line to README.md"

          # Push the branch to remote
          git push -u https://x-access-token:${{ secrets.PAT }}@github.com/Vaibhavweb-sys/test-workflow.git feature-branch

      # Step 5: Create the pull request
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.PAT }}
          commit-message: "Add new feature"
          branch: feature-branch
          base: main
          title: "Update README.md"
          body: "This PR adds a new line to the README.md file."
