name: Create PR with gh CLI

on:
  repository_dispatch:
    types: [create-pr]

permissions:
  contents: write       # Allows push access to repository
  pull-requests: write  # Allows creating pull requests

jobs:
  create-pr:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Pull latest changes
      - name: Pull latest from main
        run: |
          git fetch --prune --unshallow
          git checkout main
          git pull origin main

      # Step 3: Configure git user name and email
      - name: Configure Git user
        run: |
          git config --global user.email "github-actions@github.com"
          git config --global user.name "github-actions"

      # Step 4: Create and push a new branch using git
      - name: Create and push new branch
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Set GH_TOKEN here
        run: |
          # Create a new feature branch
          git checkout -b feature-branch

          # Add a new line to README.md
          echo "This is a new line added by the workflow using git." >> README.md
          git add README.md
          git commit -m "Add new line to README.md"

          # Push the branch to remote
          git push -u origin feature-branch

      # Step 5: Create Pull Request using gh CLI
      - name: Create Pull Request
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Set GH_TOKEN here
        run: |
          gh pr create \
            --title "Update README.md" \
            --body "This PR adds a new line to the README.md file." \
            --head feature-branch \
            --base main
